# Site settings
title: MINJOON.COM | PARADISE IS WHERE I AM
description: "for study JAVA, JVM, ELK, AWS."
url: "http://minjoon.com"
author:
  name: "Minjoon Matthew Shin"
  email: "shinminjoon@163.com"
  url: "http://minjoon.com"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/
highlighter: rouge

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      sitemap: true

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
